[project]
name = "qcodedit"
version = "0.1.0"
description = "A Code Editor Created using PyQt5"
main_script = "./src/main.py"

[packages]
QScintilla = "2.13.3"
PyQt5 = "5.15.7"

[scripts]
upgrade-pip = "python -m pip install --upgrade pip"
build-qrc = "pyrcc5 ./src/icons/resources.qrc -o ./src/resources.py"
